### ISSUE TITLE
Readme URL Entry

### ISSUE THREAD

**Issue by OnatV** [Digital-Humans-23/a4#1]
Do we have to add anything to the URL entry on Readme?

**Comment by zkf1997** [comment]
You can leave the URL entry blank if you push the video visualization files to your repo following ReadMe. 
In case your visualization files have a large size and cannot be pushed to your repo, you can upload the videos to other platforms and put URL links.

**Comment by OnatV** [comment]
Ok thank you so much for the clarification.
