### ISSUE TITLE
ex 2: human moving backwards although passing the tests

### ISSUE THREAD

**Issue by xiyichen** [Digital-Humans-23/a4#5]
I strictly followed the formula for ex2 and was able to pass the test with the autograder, but when visualizing it in Blender, the human is moving backwards, which looks different from the given demo video. 

![ex2](https://user-images.githubusercontent.com/50854238/235343360-73cbc914-c9ba-407e-8a20-88f5198aa08b.gif)

I wonder if this is accepted behavior or is there something wrong with my implementation?

**Comment by zkf1997** [comment]
It is acceptable to have different results from the example visualization as long as it satisfies the given task constraints. 
The search algorithm is to some extent stochastic and may have slightly different behaviors in different software/hardware environments. The attached result looks good to me and it can achieve full points if the automatic tests are also passed.
